cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/rm/docs/Repos/ns-allinone-3.19/ns-3.19/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/home/rm/docs/Repos/ns-allinone-3.19/ns-3.19/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 140225092322896: cxxprogram test.cpp.1.o -> testprog}\n[\'/usr/bin/g++\', \'-Wl,-O1,--sort-common,--as-needed,-z,relro\', \'test.cpp.1.o\', \'-o\', \'/home/rm/docs/Repos/ns-allinone-3.19/ns-3.19/build/.conf_check_1148cd450a973084f2ff9002c61d71c7/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\', \'-L/usr/libs\', \'-lpython3.4\']\n'
